---
deployment:
  tasks:
    - export DEPLOYPATH=/home/njhessassoc/public_html/
    - /bin/cp app/index.html $DEPLOYPATH
    - /bin/cp app/styles.css $DEPLOYPATH
    - /bin/cp -R app/images $DEPLOYPATH
    - /bin/cp -R app/assets $DEPLOYPATH
    - /bin/cp -R wordpress $DEPLOYPATH